{{- if not .Values.customConfigMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homer.fullname" . }}
  labels:
    {{- include "homer.labels" . | nindent 4 }}
data:
  config.yml: {{- .Values.config | toJson | indent 1 }}
{{- end -}}