site_name: Alex Dresko's helm charts
site_url: https://alexdresko.github.io/helm-charts/pages
theme: readthedocs
repo_url: https://github.com/alexdresko/helm-charts/pages/

plugins:
    - search
    - markdownextradata: {}


extra:
  customer:
    name: Neato
    web: www.example.com
    salt: salt.example.com    